// SERVER EVENT CODES

function Keys() {
  /////////////////// EVENTS

  // USER HANDLES
  this.SEND_USERNAME = "SEND_USERNAME";
  this.SEND_JOIN_TO_ROOM = "SEND_JOIN_TO_ROOM";
  this.SEND_LEAVE_FROM_ROOM = "SEND_LEAVE_FROM_ROOM";

  // MESSAGES
  this.SEND_MESSAGE_TO_ROOM = "SEND_MESSAGE_TO_ROOM";
  this.SEND_MESSAGE_TO_PRIVATE = "SEND_MESSAGE_TO_PRIVATE";
  this.SEND_MESSAGE_TO_GLOBAL = "SEND_MESSAGE_TO_GLOBAL";
  
  this.SEND_FETCH_USER_MESSAGES = "SEND_FETCH_USER_MESSAGES";
  this.SEND_FETCH_ROOM_MESSAGES = "SEND_FETCH_ROOM_MESSAGES";

  ////////////////// LISTENERS

  // USER HANDLES
  this.ON_USER_CONNECTED = "ON_USER_CONNECTED";
  this.ON_USER_DISCONNECTED = "ON_USER_DISCONNECTED";
  this.ON_USERNAME_CHANGED = "ON_USERNAME_CHANGED";

  this.ON_JOIN_TO_ROOM_SUCCESS = "ON_JOIN_TO_ROOM_SUCCESS";
  this.ON_JOIN_TO_ROOM_FAILED = "ON_JOIN_TO_ROOM_FAILED";
  
  this.ON_LEAVE_FROM_ROOM_SUCCESS = "ON_LEAVE_FROM_ROOM_SUCCESS";
  this.ON_LEAVE_FROM_ROOM_FAILED = "ON_LEAVE_FROM_ROOM_FAILED";

  // MESSAGES
  this.ON_GET_MESSAGE_FROM_ROOM = "ON_GET_MESSAGE_FROM_ROOM";
  this.ON_GET_MESSAGE_FROM_PRIVATE = "ON_GET_MESSAGE_FROM_PRIVATE";
  this.ON_GET_MESSAGE_FROM_GLOBAL = "ON_GET_MESSAGE_FROM_GLOBAL";

  this.ON_FETCH_USER_MESSAGES = "ON_FETCH_USER_MESSAGES";
  this.ON_FETCH_ROOM_MESSAGES = "ON_FETCH_ROOM_MESSAGES";
}

module.exports = {
  Keys: Keys
}